[[redirects]]
  from = "/api/*"
  to = "http://217.154.172.35/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/media/*"
  to = "http://217.154.172.35/media/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

